services:
  web:
    container_name: web
    build:
      context: ./web
    ports:
      - "8000:5000"
    environment:
      - USER=webuser
    depends_on:
      - redis
  redis:
    container_name: redis
    image: "redis:alpine"